language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database hotdb;" -U postgres

env:
  - SECRET_KEY='potato' DEBUG=True DB_NAME='hotdb' DB_USER='postgres' DB_HOST='localhost'

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python hott/manage.py migrate
  - coverage run hott/manage.py test hott

after_success:
  - coveralls

notifications:
  email: false