# Generated by Django 2.0.5 on 2018-05-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hottprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hottprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hottprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hottprofile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='hottprofile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='hottprofile',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hottprofile',
            name='longitutde',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
