# Generated by Django 2.0.5 on 2018-05-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_profile', '0002_auto_20180521_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottprofile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hottprofile',
            name='longitutde',
            field=models.FloatField(null=True),
        ),
    ]
