# Generated by Django 2.0.5 on 2018-05-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_overlays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('description', models.CharField(default='DEFAULT', max_length=180)),
            ],
        ),
    ]
