# Generated by Django 2.0.5 on 2018-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_overlays', '0002_entertainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
