# Generated by Django 2.0.5 on 2018-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_overlays', '0003_auto_20180522_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='description',
            field=models.CharField(default='DEFAULT', max_length=180, null=True),
        ),
    ]
