# Generated by Django 2.0.5 on 2018-05-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_overlays', '0004_auto_20180522_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.CharField(default='DEFAULT', max_length=180)),
            ],
        ),
    ]
