# Generated by Django 2.0.5 on 2018-05-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_overlays', '0005_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(default='DEFAULT', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
