# Generated by Django 2.0.5 on 2018-05-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hott_overlays', '0007_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirtiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('description', models.CharField(default='DEFAULT', max_length=180, null=True)),
            ],
        ),
    ]
